
version: '3'
services: 
  client: 
      image: node:12.18.4
      ports:
          - 8080:8080
      volumes:
      - type: bind
        source: ./client
        target: /code
      working_dir: /code
      command: bash -c "npn install & npm run dev"
  api:
      image: node:12.18.4
      ports:
        - 3000:3000
      environment:
        - DB_CONNECTION=mongodb://footballers-admin:footballers-pass@db:27017
        - DB_NAME=footballers
      volumes:
      - type: bind
        source: ./server
        target: /code
      working_dir: /code
      command: bash -c "npn install & npm run dev"
      depends_on: 
      - db
  db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=footballers-admin
      - MONGO_INITDB_DATABASE=footballers
      - MONGO_INITDB_ROOT_PASSWORD=footballers-pass
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro"
volumes:
  dbdata:
      